### ISSUE TITLE
cargo build  error 

### ISSUE THREAD

**Issue by JongAnYoo** [Maccraft123/peroxide#1]
This is my first question ^^
Watch aya neo multi boot on youtube
I've been wanting to try it.
However, I am getting an error while compiling.

-----------------------------------------------------------------

[yjaking@SteamOSFE src]$ cargo build
    Updating git repository `https://github.com/Maccraft123/aski.git`
    Updating crates.io index
    Updating git repository `https://github.com/Maccraft123/ozone.git`
    Updating git repository `https://github.com/R-ARM/ez_input.git`
  Downloaded serde_repr v0.1.9
  Downloaded thiserror v1.0.35
  Downloaded thiserror-impl v1.0.35
  Downloaded wyz v0.5.0
  Downloaded uuid v0.8.2
  Downloaded crc v1.8.1
  Downloaded bit_field v0.10.1
  Downloaded funty v2.0.0
  Downloaded build_const v0.2.2
  Downloaded radium v0.7.0
  Downloaded proc-macro2 v1.0.43
  Downloaded synstructure v0.12.6
  Downloaded tap v1.0.1
  Downloaded uuid v1.1.2
  Downloaded smallvec v1.9.0
  Downloaded signal-hook v0.3.14
  Downloaded signal-hook-mio v0.2.3
  Downloaded signal-hook-registry v1.4.0
  Downloaded unicode-ident v1.0.4
  Downloaded syn v1.0.100
  Downloaded ucs2 v0.3.2
  Downloaded uefi-macros v0.8.1
  Downloaded autocfg v1.1.0
  Downloaded cfg-if v1.0.0
  Downloaded cc v1.0.73
  Downloaded memoffset v0.6.5
  Downloaded log v0.4.17
  Downloaded pin-utils v0.1.0
  Downloaded parking_lot_core v0.9.3
  Downloaded scopeguard v1.1.0
  Downloaded unicode-xid v0.2.4
  Downloaded serde_derive v1.0.145
  Downloaded parking_lot v0.12.1
  Downloaded serde v1.0.145
  Downloaded mio v0.8.4
  Downloaded object v0.29.0
  Downloaded failure v0.1.8
  Downloaded failure_derive v0.1.8
  Downloaded rustc-demangle v0.1.21
  Downloaded quote v1.0.21
  Downloaded miniz_oxide v0.5.4
  Downloaded aho-corasick v0.7.19
  Downloaded regex v1.6.0
  Downloaded regex-syntax v0.6.27
  Downloaded lazy_static v1.4.0
  Downloaded nix v0.25.0
  Downloaded memchr v2.5.0
  Downloaded getrandom v0.2.7
  Downloaded lock_api v0.4.9
  Downloaded bitflags v1.3.2
  Downloaded backtrace v0.3.66
  Downloaded anyhow v1.0.65
  Downloaded uefi v0.17.0
  Downloaded nix v0.23.1
  Downloaded libc v0.2.133
  Downloaded gimli v0.26.2
  Downloaded crossterm v0.25.0
  Downloaded byteorder v1.4.3
  Downloaded adler v1.0.2
  Downloaded syscalls v0.6.6
  Downloaded bitvec v1.0.1
  Downloaded addr2line v0.17.0
  Downloaded gpt v3.0.0
  Downloaded evdev v0.11.7
  Downloaded efivar v0.2.1
  Downloaded 65 crates (5.0 MB) in 1.36s
   Compiling proc-macro2 v1.0.43
   Compiling libc v0.2.133
   Compiling unicode-ident v1.0.4
   Compiling quote v1.0.21
   Compiling syn v1.0.100
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling bitflags v1.3.2
   Compiling log v0.4.17
   Compiling memchr v2.5.0
   Compiling serde_derive v1.0.145
   Compiling serde v1.0.145
   Compiling cc v1.0.73
   Compiling radium v0.7.0
   Compiling gimli v0.26.2
   Compiling signal-hook v0.3.14
   Compiling build_const v0.2.2
   Compiling failure_derive v0.1.8
   Compiling thiserror v1.0.35
   Compiling adler v1.0.2
   Compiling unicode-xid v0.2.4
   Compiling parking_lot_core v0.9.3
   Compiling tap v1.0.1
   Compiling rustc-demangle v0.1.21
   Compiling funty v2.0.0
   Compiling scopeguard v1.1.0
   Compiling smallvec v1.9.0
   Compiling bit_field v0.10.1
   Compiling anyhow v1.0.65
   Compiling lazy_static v1.4.0
   Compiling byteorder v1.4.3
   Compiling pin-utils v0.1.0
   Compiling regex-syntax v0.6.27
   Compiling uuid v1.1.2
   Compiling crc v1.8.1
   Compiling miniz_oxide v0.5.4
   Compiling wyz v0.5.0
   Compiling memoffset v0.6.5
   Compiling lock_api v0.4.9
   Compiling ucs2 v0.3.2
   Compiling bitvec v1.0.1
   Compiling object v0.29.0
   Compiling aho-corasick v0.7.19
   Compiling backtrace v0.3.66
   Compiling signal-hook-registry v1.4.0
   Compiling getrandom v0.2.7
   Compiling nix v0.23.1
   Compiling mio v0.8.4
   Compiling nix v0.25.0
   Compiling addr2line v0.17.0
   Compiling regex v1.6.0
   Compiling parking_lot v0.12.1
   Compiling signal-hook-mio v0.2.3
   Compiling crossterm v0.25.0
   Compiling synstructure v0.12.6
   Compiling thiserror-impl v1.0.35
   Compiling uefi-macros v0.8.1
   Compiling serde_repr v0.1.9
   Compiling uefi v0.17.0
   Compiling failure v0.1.8
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/yjaking/.cargo/registry/src/github.com-1ecc6299db9ec823/uefi-0.17.0/src/lib.rs:26:1
   |
26 | #![feature(abi_efiapi)]
   | ^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/yjaking/.cargo/registry/src/github.com-1ecc6299db9ec823/uefi-0.17.0/src/lib.rs:27:1
   |
27 | #![feature(maybe_uninit_slice)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/yjaking/.cargo/registry/src/github.com-1ecc6299db9ec823/uefi-0.17.0/src/lib.rs:28:1
   |
28 | #![feature(negative_impls)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/yjaking/.cargo/registry/src/github.com-1ecc6299db9ec823/uefi-0.17.0/src/lib.rs:29:1
   |
29 | #![feature(ptr_metadata)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/yjaking/.cargo/registry/src/github.com-1ecc6299db9ec823/uefi-0.17.0/src/lib.rs:30:31
   |
30 | #![cfg_attr(feature = "exts", feature(vec_into_raw_parts))]
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/yjaking/.cargo/registry/src/github.com-1ecc6299db9ec823/uefi-0.17.0/src/lib.rs:27:12
   |
27 | #![feature(maybe_uninit_slice)]
   |            ^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/yjaking/.cargo/registry/src/github.com-1ecc6299db9ec823/uefi-0.17.0/src/lib.rs:29:12
   |
29 | #![feature(ptr_metadata)]
   |            ^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/yjaking/.cargo/registry/src/github.com-1ecc6299db9ec823/uefi-0.17.0/src/lib.rs:30:39
   |
30 | #![cfg_attr(feature = "exts", feature(vec_into_raw_parts))]
   |                                       ^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `uefi` due to 8 previous errors
warning: build failed, waiting for other jobs to finish...
[yjaking@SteamOSFE src]$

**Comment by Maccraft123** [comment]
yeah you gotta have nightly toolchain

pon., 26 wrz 2022, 16:21 użytkownik JongAnYoo ***@***.***>
napisał:

**Comment by JongAnYoo** [comment]
thanks for the quick reply ^^
However, I am Korean TT
Can you explain more easily?

**Comment by JongAnYoo** [comment]
[yjaking@SteamOSFE src]$ rustup run nightly rustc --version
rustc 1.66.0-nightly (f5193a9fc 2022-09-25)
[yjaking@SteamOSFE src]$ rustup default nightly
info: using existing install for 'nightly-x86_64-unknown-linux-gnu'
info: default toolchain set to 'nightly-x86_64-unknown-linux-gnu'


nightly toolchain after....

[yjaking@SteamOSFE src]$ cargo build
   Compiling proc-macro2 v1.0.43
   Compiling unicode-ident v1.0.4
   Compiling libc v0.2.133
   Compiling quote v1.0.21
   Compiling syn v1.0.100
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling bitflags v1.3.2
   Compiling log v0.4.17
   Compiling memchr v2.5.0
   Compiling serde_derive v1.0.145
   Compiling serde v1.0.145
   Compiling cc v1.0.73
   Compiling radium v0.7.0
   Compiling parking_lot_core v0.9.3
   Compiling failure_derive v0.1.8
   Compiling gimli v0.26.2
   Compiling build_const v0.2.2
   Compiling adler v1.0.2
   Compiling unicode-xid v0.2.4
   Compiling thiserror v1.0.35
   Compiling tap v1.0.1
   Compiling signal-hook v0.3.14
   Compiling wyz v0.5.0
   Compiling crc v1.8.1
   Compiling miniz_oxide v0.5.4
   Compiling scopeguard v1.1.0
   Compiling rustc-demangle v0.1.21
   Compiling smallvec v1.9.0
   Compiling funty v2.0.0
   Compiling memoffset v0.6.5
   Compiling lock_api v0.4.9
   Compiling anyhow v1.0.65
   Compiling bit_field v0.10.1
   Compiling lazy_static v1.4.0
   Compiling pin-utils v0.1.0
   Compiling byteorder v1.4.3
   Compiling ucs2 v0.3.2
   Compiling uuid v1.1.2
   Compiling regex-syntax v0.6.27
   Compiling object v0.29.0
   Compiling aho-corasick v0.7.19
   Compiling bitvec v1.0.1
   Compiling backtrace v0.3.66
   Compiling signal-hook-registry v1.4.0
   Compiling getrandom v0.2.7
   Compiling nix v0.23.1
   Compiling mio v0.8.4
   Compiling nix v0.25.0
   Compiling parking_lot v0.12.1
   Compiling signal-hook-mio v0.2.3
   Compiling crossterm v0.25.0
   Compiling addr2line v0.17.0
   Compiling regex v1.6.0
   Compiling synstructure v0.12.6
   Compiling thiserror-impl v1.0.35
   Compiling uefi-macros v0.8.1
   Compiling serde_repr v0.1.9
   Compiling uefi v0.17.0
   Compiling failure v0.1.8
   Compiling evdev v0.11.7
   Compiling ez_input v0.1.0 (https://github.com/R-ARM/ez_input.git?branch=main#6bc10962)
   Compiling aski v0.1.0 (https://github.com/Maccraft123/aski.git?branch=main#8e925475)
   Compiling uuid v0.8.2
   Compiling syscalls v0.6.6
   Compiling efivar v0.2.1
   Compiling gpt v3.0.0
   Compiling ozone v0.1.0 (https://github.com/Maccraft123/ozone.git?branch=main#ee10af82)
   Compiling peroxide v0.1.0 (/home/yjaking/.cargo/bin/peroxide-main)
warning: unused import: `nix::fcntl::readlink`
  --> src/uefi.rs:17:5
   |
17 | use nix::fcntl::readlink;
   |     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `RawFd`
  --> src/boot.rs:19:34
   |
19 | use std::os::unix::io::{AsRawFd, RawFd};
   |                                  ^^^^^

warning: variable does not need to be mutable
  --> src/main.rs:18:9
   |
18 |     let mut entries = entry::enumerate_all();
   |         ----^^^^^^^
   |         |
   |         help: remove this `mut`
   |
   = note: `#[warn(unused_mut)]` on by default

warning: fields `version` and `machine_id` are never read
  --> src/bootloaderspec.rs:17:5
   |
15 | pub struct FreedesktopBootEntry {
   |            -------------------- fields in this struct
16 |     title: Option<String>,
17 |     version: Option<String>,
   |     ^^^^^^^
18 |     machine_id: Option<String>,
   |     ^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default
   = note: `FreedesktopBootEntry` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis

warning: `peroxide` (bin "peroxide") generated 4 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 17.64s
[yjaking@SteamOSFE src]$

**Comment by JongAnYoo** [comment]
a.... it;s warning    build success? wow!!! thanks!!!

**Comment by JongAnYoo** [comment]
How can I apply the built executable file to AYA Neo?

**Comment by JongAnYoo** [comment]
How can I apply the built executable file to AYA Neo?

**Comment by JongAnYoo** [comment]
Thanks it has been resolved.
